/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccountTypeRouteImport } from './routes/account-type'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as RiderHomeRouteImport } from './routes/rider.home'
import { Route as RiderProfileRouteImport } from './routes/rider.profile'
import { Route as RiderRequestsRouteImport } from './routes/rider.requests'
import { Route as RiderTripsRouteImport } from './routes/rider.trips'
import { Route as RiderWalletRouteImport } from './routes/rider.wallet'
import { Route as AuthenticatedStudentActivityRouteImport } from './routes/_authenticated/student.activity'
import { Route as AuthenticatedStudentHomeRouteImport } from './routes/_authenticated/student.home'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/student.profile'
import { Route as AuthenticatedStudentRidesIndexRouteImport } from './routes/_authenticated/student.rides.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTypeRoute = AccountTypeRouteImport.update({
  id: '/account-type',
  path: '/account-type',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderHomeRoute = RiderHomeRouteImport.update({
  id: '/rider/home',
  path: '/rider/home',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderProfileRoute = RiderProfileRouteImport.update({
  id: '/rider/profile',
  path: '/rider/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRequestsRoute = RiderRequestsRouteImport.update({
  id: '/rider/requests',
  path: '/rider/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderTripsRoute = RiderTripsRouteImport.update({
  id: '/rider/trips',
  path: '/rider/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderWalletRoute = RiderWalletRouteImport.update({
  id: '/rider/wallet',
  path: '/rider/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentActivityRoute =
  AuthenticatedStudentActivityRouteImport.update({
    id: '/student/activity',
    path: '/student/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentHomeRoute =
  AuthenticatedStudentHomeRouteImport.update({
    id: '/student/home',
    path: '/student/home',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/student/profile',
    path: '/student/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentRidesIndexRoute =
  AuthenticatedStudentRidesIndexRouteImport.update({
    id: '/student/rides/',
    path: '/student/rides/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-type': typeof AccountTypeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verification': typeof VerificationRoute
  '/rider/home': typeof RiderHomeRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/requests': typeof RiderRequestsRoute
  '/rider/trips': typeof RiderTripsRoute
  '/rider/wallet': typeof RiderWalletRoute
  '/student/activity': typeof AuthenticatedStudentActivityRoute
  '/student/home': typeof AuthenticatedStudentHomeRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/rides/': typeof AuthenticatedStudentRidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-type': typeof AccountTypeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verification': typeof VerificationRoute
  '/rider/home': typeof RiderHomeRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/requests': typeof RiderRequestsRoute
  '/rider/trips': typeof RiderTripsRoute
  '/rider/wallet': typeof RiderWalletRoute
  '/student/activity': typeof AuthenticatedStudentActivityRoute
  '/student/home': typeof AuthenticatedStudentHomeRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/rides': typeof AuthenticatedStudentRidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account-type': typeof AccountTypeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verification': typeof VerificationRoute
  '/rider/home': typeof RiderHomeRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/requests': typeof RiderRequestsRoute
  '/rider/trips': typeof RiderTripsRoute
  '/rider/wallet': typeof RiderWalletRoute
  '/_authenticated/student/activity': typeof AuthenticatedStudentActivityRoute
  '/_authenticated/student/home': typeof AuthenticatedStudentHomeRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/student/rides/': typeof AuthenticatedStudentRidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-type'
    | '/login'
    | '/signup'
    | '/verification'
    | '/rider/home'
    | '/rider/profile'
    | '/rider/requests'
    | '/rider/trips'
    | '/rider/wallet'
    | '/student/activity'
    | '/student/home'
    | '/student/profile'
    | '/student/rides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-type'
    | '/login'
    | '/signup'
    | '/verification'
    | '/rider/home'
    | '/rider/profile'
    | '/rider/requests'
    | '/rider/trips'
    | '/rider/wallet'
    | '/student/activity'
    | '/student/home'
    | '/student/profile'
    | '/student/rides'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account-type'
    | '/login'
    | '/signup'
    | '/verification'
    | '/rider/home'
    | '/rider/profile'
    | '/rider/requests'
    | '/rider/trips'
    | '/rider/wallet'
    | '/_authenticated/student/activity'
    | '/_authenticated/student/home'
    | '/_authenticated/student/profile'
    | '/_authenticated/student/rides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountTypeRoute: typeof AccountTypeRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerificationRoute: typeof VerificationRoute
  RiderHomeRoute: typeof RiderHomeRoute
  RiderProfileRoute: typeof RiderProfileRoute
  RiderRequestsRoute: typeof RiderRequestsRoute
  RiderTripsRoute: typeof RiderTripsRoute
  RiderWalletRoute: typeof RiderWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-type': {
      id: '/account-type'
      path: '/account-type'
      fullPath: '/account-type'
      preLoaderRoute: typeof AccountTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/home': {
      id: '/rider/home'
      path: '/rider/home'
      fullPath: '/rider/home'
      preLoaderRoute: typeof RiderHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/profile': {
      id: '/rider/profile'
      path: '/rider/profile'
      fullPath: '/rider/profile'
      preLoaderRoute: typeof RiderProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/requests': {
      id: '/rider/requests'
      path: '/rider/requests'
      fullPath: '/rider/requests'
      preLoaderRoute: typeof RiderRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/trips': {
      id: '/rider/trips'
      path: '/rider/trips'
      fullPath: '/rider/trips'
      preLoaderRoute: typeof RiderTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/wallet': {
      id: '/rider/wallet'
      path: '/rider/wallet'
      fullPath: '/rider/wallet'
      preLoaderRoute: typeof RiderWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student/activity': {
      id: '/_authenticated/student/activity'
      path: '/student/activity'
      fullPath: '/student/activity'
      preLoaderRoute: typeof AuthenticatedStudentActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/home': {
      id: '/_authenticated/student/home'
      path: '/student/home'
      fullPath: '/student/home'
      preLoaderRoute: typeof AuthenticatedStudentHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/rides/': {
      id: '/_authenticated/student/rides/'
      path: '/student/rides'
      fullPath: '/student/rides/'
      preLoaderRoute: typeof AuthenticatedStudentRidesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudentActivityRoute: typeof AuthenticatedStudentActivityRoute
  AuthenticatedStudentHomeRoute: typeof AuthenticatedStudentHomeRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentRidesIndexRoute: typeof AuthenticatedStudentRidesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudentActivityRoute: AuthenticatedStudentActivityRoute,
  AuthenticatedStudentHomeRoute: AuthenticatedStudentHomeRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedStudentRidesIndexRoute: AuthenticatedStudentRidesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountTypeRoute: AccountTypeRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerificationRoute: VerificationRoute,
  RiderHomeRoute: RiderHomeRoute,
  RiderProfileRoute: RiderProfileRoute,
  RiderRequestsRoute: RiderRequestsRoute,
  RiderTripsRoute: RiderTripsRoute,
  RiderWalletRoute: RiderWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
