/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccountTypeRouteImport } from './routes/account-type'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RiderSignupRouteImport } from './routes/rider-signup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as AuthenticatedAccountSetupRouteImport } from './routes/_authenticated/account-setup'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedRiderRouteImport } from './routes/_authenticated/rider'
import { Route as AuthenticatedRiderApplicationRouteImport } from './routes/_authenticated/rider-application'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedAdminLocationSuggestionsRouteImport } from './routes/_authenticated/admin.location-suggestions'
import { Route as AuthenticatedAdminLocationsRouteImport } from './routes/_authenticated/admin.locations'
import { Route as AuthenticatedAdminRidersRouteImport } from './routes/_authenticated/admin.riders'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminVerificationRouteImport } from './routes/_authenticated/admin.verification'
import { Route as AuthenticatedRiderHomeRouteImport } from './routes/_authenticated/rider.home'
import { Route as AuthenticatedRiderProfileRouteImport } from './routes/_authenticated/rider.profile'
import { Route as AuthenticatedRiderRequestsRouteImport } from './routes/_authenticated/rider.requests'
import { Route as AuthenticatedRiderSuggestLocationRouteImport } from './routes/_authenticated/rider.suggest-location'
import { Route as AuthenticatedRiderTripsRouteImport } from './routes/_authenticated/rider.trips'
import { Route as AuthenticatedRiderWalletRouteImport } from './routes/_authenticated/rider.wallet'
import { Route as AuthenticatedStudentActivityRouteImport } from './routes/_authenticated/student.activity'
import { Route as AuthenticatedStudentHomeRouteImport } from './routes/_authenticated/student.home'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/student.profile'
import { Route as AuthenticatedStudentRequestRouteImport } from './routes/_authenticated/student.request'
import { Route as AuthenticatedStudentSuggestLocationRouteImport } from './routes/_authenticated/student.suggest-location'
import { Route as AuthenticatedStudentRidesIndexRouteImport } from './routes/_authenticated/student.rides.index'
import { Route as AuthenticatedStudentRidesIdRouteImport } from './routes/_authenticated/student.rides.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTypeRoute = AccountTypeRouteImport.update({
  id: '/account-type',
  path: '/account-type',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderSignupRoute = RiderSignupRouteImport.update({
  id: '/rider-signup',
  path: '/rider-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountSetupRoute =
  AuthenticatedAccountSetupRouteImport.update({
    id: '/account-setup',
    path: '/account-setup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiderRoute = AuthenticatedRiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiderApplicationRoute =
  AuthenticatedRiderApplicationRouteImport.update({
    id: '/rider-application',
    path: '/rider-application',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLocationSuggestionsRoute =
  AuthenticatedAdminLocationSuggestionsRouteImport.update({
    id: '/location-suggestions',
    path: '/location-suggestions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLocationsRoute =
  AuthenticatedAdminLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRidersRoute =
  AuthenticatedAdminRidersRouteImport.update({
    id: '/riders',
    path: '/riders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVerificationRoute =
  AuthenticatedAdminVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedRiderHomeRoute = AuthenticatedRiderHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRiderRoute,
} as any)
const AuthenticatedRiderProfileRoute =
  AuthenticatedRiderProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRiderRoute,
  } as any)
const AuthenticatedRiderRequestsRoute =
  AuthenticatedRiderRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedRiderRoute,
  } as any)
const AuthenticatedRiderSuggestLocationRoute =
  AuthenticatedRiderSuggestLocationRouteImport.update({
    id: '/suggest-location',
    path: '/suggest-location',
    getParentRoute: () => AuthenticatedRiderRoute,
  } as any)
const AuthenticatedRiderTripsRoute = AuthenticatedRiderTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRiderRoute,
} as any)
const AuthenticatedRiderWalletRoute =
  AuthenticatedRiderWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedRiderRoute,
  } as any)
const AuthenticatedStudentActivityRoute =
  AuthenticatedStudentActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentHomeRoute =
  AuthenticatedStudentHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentRequestRoute =
  AuthenticatedStudentRequestRouteImport.update({
    id: '/request',
    path: '/request',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentSuggestLocationRoute =
  AuthenticatedStudentSuggestLocationRouteImport.update({
    id: '/suggest-location',
    path: '/suggest-location',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentRidesIndexRoute =
  AuthenticatedStudentRidesIndexRouteImport.update({
    id: '/rides/',
    path: '/rides/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentRidesIdRoute =
  AuthenticatedStudentRidesIdRouteImport.update({
    id: '/rides/$id',
    path: '/rides/$id',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-type': typeof AccountTypeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rider-signup': typeof RiderSignupRoute
  '/signup': typeof SignupRoute
  '/verification': typeof VerificationRoute
  '/account-setup': typeof AuthenticatedAccountSetupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/rider': typeof AuthenticatedRiderRouteWithChildren
  '/rider-application': typeof AuthenticatedRiderApplicationRoute
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/admin/location-suggestions': typeof AuthenticatedAdminLocationSuggestionsRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/riders': typeof AuthenticatedAdminRidersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/rider/home': typeof AuthenticatedRiderHomeRoute
  '/rider/profile': typeof AuthenticatedRiderProfileRoute
  '/rider/requests': typeof AuthenticatedRiderRequestsRoute
  '/rider/suggest-location': typeof AuthenticatedRiderSuggestLocationRoute
  '/rider/trips': typeof AuthenticatedRiderTripsRoute
  '/rider/wallet': typeof AuthenticatedRiderWalletRoute
  '/student/activity': typeof AuthenticatedStudentActivityRoute
  '/student/home': typeof AuthenticatedStudentHomeRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/request': typeof AuthenticatedStudentRequestRoute
  '/student/suggest-location': typeof AuthenticatedStudentSuggestLocationRoute
  '/student/rides/$id': typeof AuthenticatedStudentRidesIdRoute
  '/student/rides/': typeof AuthenticatedStudentRidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-type': typeof AccountTypeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rider-signup': typeof RiderSignupRoute
  '/signup': typeof SignupRoute
  '/verification': typeof VerificationRoute
  '/account-setup': typeof AuthenticatedAccountSetupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/rider': typeof AuthenticatedRiderRouteWithChildren
  '/rider-application': typeof AuthenticatedRiderApplicationRoute
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/admin/location-suggestions': typeof AuthenticatedAdminLocationSuggestionsRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/riders': typeof AuthenticatedAdminRidersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/rider/home': typeof AuthenticatedRiderHomeRoute
  '/rider/profile': typeof AuthenticatedRiderProfileRoute
  '/rider/requests': typeof AuthenticatedRiderRequestsRoute
  '/rider/suggest-location': typeof AuthenticatedRiderSuggestLocationRoute
  '/rider/trips': typeof AuthenticatedRiderTripsRoute
  '/rider/wallet': typeof AuthenticatedRiderWalletRoute
  '/student/activity': typeof AuthenticatedStudentActivityRoute
  '/student/home': typeof AuthenticatedStudentHomeRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/request': typeof AuthenticatedStudentRequestRoute
  '/student/suggest-location': typeof AuthenticatedStudentSuggestLocationRoute
  '/student/rides/$id': typeof AuthenticatedStudentRidesIdRoute
  '/student/rides': typeof AuthenticatedStudentRidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account-type': typeof AccountTypeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rider-signup': typeof RiderSignupRoute
  '/signup': typeof SignupRoute
  '/verification': typeof VerificationRoute
  '/_authenticated/account-setup': typeof AuthenticatedAccountSetupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/rider': typeof AuthenticatedRiderRouteWithChildren
  '/_authenticated/rider-application': typeof AuthenticatedRiderApplicationRoute
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/admin/location-suggestions': typeof AuthenticatedAdminLocationSuggestionsRoute
  '/_authenticated/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/_authenticated/admin/riders': typeof AuthenticatedAdminRidersRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/_authenticated/rider/home': typeof AuthenticatedRiderHomeRoute
  '/_authenticated/rider/profile': typeof AuthenticatedRiderProfileRoute
  '/_authenticated/rider/requests': typeof AuthenticatedRiderRequestsRoute
  '/_authenticated/rider/suggest-location': typeof AuthenticatedRiderSuggestLocationRoute
  '/_authenticated/rider/trips': typeof AuthenticatedRiderTripsRoute
  '/_authenticated/rider/wallet': typeof AuthenticatedRiderWalletRoute
  '/_authenticated/student/activity': typeof AuthenticatedStudentActivityRoute
  '/_authenticated/student/home': typeof AuthenticatedStudentHomeRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/student/request': typeof AuthenticatedStudentRequestRoute
  '/_authenticated/student/suggest-location': typeof AuthenticatedStudentSuggestLocationRoute
  '/_authenticated/student/rides/$id': typeof AuthenticatedStudentRidesIdRoute
  '/_authenticated/student/rides/': typeof AuthenticatedStudentRidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-type'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/rider-signup'
    | '/signup'
    | '/verification'
    | '/account-setup'
    | '/admin'
    | '/rider'
    | '/rider-application'
    | '/student'
    | '/admin/location-suggestions'
    | '/admin/locations'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/verification'
    | '/rider/home'
    | '/rider/profile'
    | '/rider/requests'
    | '/rider/suggest-location'
    | '/rider/trips'
    | '/rider/wallet'
    | '/student/activity'
    | '/student/home'
    | '/student/profile'
    | '/student/request'
    | '/student/suggest-location'
    | '/student/rides/$id'
    | '/student/rides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-type'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/rider-signup'
    | '/signup'
    | '/verification'
    | '/account-setup'
    | '/admin'
    | '/rider'
    | '/rider-application'
    | '/student'
    | '/admin/location-suggestions'
    | '/admin/locations'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/verification'
    | '/rider/home'
    | '/rider/profile'
    | '/rider/requests'
    | '/rider/suggest-location'
    | '/rider/trips'
    | '/rider/wallet'
    | '/student/activity'
    | '/student/home'
    | '/student/profile'
    | '/student/request'
    | '/student/suggest-location'
    | '/student/rides/$id'
    | '/student/rides'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account-type'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/rider-signup'
    | '/signup'
    | '/verification'
    | '/_authenticated/account-setup'
    | '/_authenticated/admin'
    | '/_authenticated/rider'
    | '/_authenticated/rider-application'
    | '/_authenticated/student'
    | '/_authenticated/admin/location-suggestions'
    | '/_authenticated/admin/locations'
    | '/_authenticated/admin/riders'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/verification'
    | '/_authenticated/rider/home'
    | '/_authenticated/rider/profile'
    | '/_authenticated/rider/requests'
    | '/_authenticated/rider/suggest-location'
    | '/_authenticated/rider/trips'
    | '/_authenticated/rider/wallet'
    | '/_authenticated/student/activity'
    | '/_authenticated/student/home'
    | '/_authenticated/student/profile'
    | '/_authenticated/student/request'
    | '/_authenticated/student/suggest-location'
    | '/_authenticated/student/rides/$id'
    | '/_authenticated/student/rides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountTypeRoute: typeof AccountTypeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RiderSignupRoute: typeof RiderSignupRoute
  SignupRoute: typeof SignupRoute
  VerificationRoute: typeof VerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-type': {
      id: '/account-type'
      path: '/account-type'
      fullPath: '/account-type'
      preLoaderRoute: typeof AccountTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider-signup': {
      id: '/rider-signup'
      path: '/rider-signup'
      fullPath: '/rider-signup'
      preLoaderRoute: typeof RiderSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account-setup': {
      id: '/_authenticated/account-setup'
      path: '/account-setup'
      fullPath: '/account-setup'
      preLoaderRoute: typeof AuthenticatedAccountSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rider': {
      id: '/_authenticated/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof AuthenticatedRiderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rider-application': {
      id: '/_authenticated/rider-application'
      path: '/rider-application'
      fullPath: '/rider-application'
      preLoaderRoute: typeof AuthenticatedRiderApplicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/location-suggestions': {
      id: '/_authenticated/admin/location-suggestions'
      path: '/location-suggestions'
      fullPath: '/admin/location-suggestions'
      preLoaderRoute: typeof AuthenticatedAdminLocationSuggestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/locations': {
      id: '/_authenticated/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AuthenticatedAdminLocationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/riders': {
      id: '/_authenticated/admin/riders'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AuthenticatedAdminRidersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/verification': {
      id: '/_authenticated/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AuthenticatedAdminVerificationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/rider/home': {
      id: '/_authenticated/rider/home'
      path: '/home'
      fullPath: '/rider/home'
      preLoaderRoute: typeof AuthenticatedRiderHomeRouteImport
      parentRoute: typeof AuthenticatedRiderRoute
    }
    '/_authenticated/rider/profile': {
      id: '/_authenticated/rider/profile'
      path: '/profile'
      fullPath: '/rider/profile'
      preLoaderRoute: typeof AuthenticatedRiderProfileRouteImport
      parentRoute: typeof AuthenticatedRiderRoute
    }
    '/_authenticated/rider/requests': {
      id: '/_authenticated/rider/requests'
      path: '/requests'
      fullPath: '/rider/requests'
      preLoaderRoute: typeof AuthenticatedRiderRequestsRouteImport
      parentRoute: typeof AuthenticatedRiderRoute
    }
    '/_authenticated/rider/suggest-location': {
      id: '/_authenticated/rider/suggest-location'
      path: '/suggest-location'
      fullPath: '/rider/suggest-location'
      preLoaderRoute: typeof AuthenticatedRiderSuggestLocationRouteImport
      parentRoute: typeof AuthenticatedRiderRoute
    }
    '/_authenticated/rider/trips': {
      id: '/_authenticated/rider/trips'
      path: '/trips'
      fullPath: '/rider/trips'
      preLoaderRoute: typeof AuthenticatedRiderTripsRouteImport
      parentRoute: typeof AuthenticatedRiderRoute
    }
    '/_authenticated/rider/wallet': {
      id: '/_authenticated/rider/wallet'
      path: '/wallet'
      fullPath: '/rider/wallet'
      preLoaderRoute: typeof AuthenticatedRiderWalletRouteImport
      parentRoute: typeof AuthenticatedRiderRoute
    }
    '/_authenticated/student/activity': {
      id: '/_authenticated/student/activity'
      path: '/activity'
      fullPath: '/student/activity'
      preLoaderRoute: typeof AuthenticatedStudentActivityRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/home': {
      id: '/_authenticated/student/home'
      path: '/home'
      fullPath: '/student/home'
      preLoaderRoute: typeof AuthenticatedStudentHomeRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/request': {
      id: '/_authenticated/student/request'
      path: '/request'
      fullPath: '/student/request'
      preLoaderRoute: typeof AuthenticatedStudentRequestRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/suggest-location': {
      id: '/_authenticated/student/suggest-location'
      path: '/suggest-location'
      fullPath: '/student/suggest-location'
      preLoaderRoute: typeof AuthenticatedStudentSuggestLocationRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/rides/': {
      id: '/_authenticated/student/rides/'
      path: '/rides'
      fullPath: '/student/rides/'
      preLoaderRoute: typeof AuthenticatedStudentRidesIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/rides/$id': {
      id: '/_authenticated/student/rides/$id'
      path: '/rides/$id'
      fullPath: '/student/rides/$id'
      preLoaderRoute: typeof AuthenticatedStudentRidesIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLocationSuggestionsRoute: typeof AuthenticatedAdminLocationSuggestionsRoute
  AuthenticatedAdminLocationsRoute: typeof AuthenticatedAdminLocationsRoute
  AuthenticatedAdminRidersRoute: typeof AuthenticatedAdminRidersRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminVerificationRoute: typeof AuthenticatedAdminVerificationRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLocationSuggestionsRoute:
    AuthenticatedAdminLocationSuggestionsRoute,
  AuthenticatedAdminLocationsRoute: AuthenticatedAdminLocationsRoute,
  AuthenticatedAdminRidersRoute: AuthenticatedAdminRidersRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminVerificationRoute: AuthenticatedAdminVerificationRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRiderRouteChildren {
  AuthenticatedRiderHomeRoute: typeof AuthenticatedRiderHomeRoute
  AuthenticatedRiderProfileRoute: typeof AuthenticatedRiderProfileRoute
  AuthenticatedRiderRequestsRoute: typeof AuthenticatedRiderRequestsRoute
  AuthenticatedRiderSuggestLocationRoute: typeof AuthenticatedRiderSuggestLocationRoute
  AuthenticatedRiderTripsRoute: typeof AuthenticatedRiderTripsRoute
  AuthenticatedRiderWalletRoute: typeof AuthenticatedRiderWalletRoute
}

const AuthenticatedRiderRouteChildren: AuthenticatedRiderRouteChildren = {
  AuthenticatedRiderHomeRoute: AuthenticatedRiderHomeRoute,
  AuthenticatedRiderProfileRoute: AuthenticatedRiderProfileRoute,
  AuthenticatedRiderRequestsRoute: AuthenticatedRiderRequestsRoute,
  AuthenticatedRiderSuggestLocationRoute:
    AuthenticatedRiderSuggestLocationRoute,
  AuthenticatedRiderTripsRoute: AuthenticatedRiderTripsRoute,
  AuthenticatedRiderWalletRoute: AuthenticatedRiderWalletRoute,
}

const AuthenticatedRiderRouteWithChildren =
  AuthenticatedRiderRoute._addFileChildren(AuthenticatedRiderRouteChildren)

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentActivityRoute: typeof AuthenticatedStudentActivityRoute
  AuthenticatedStudentHomeRoute: typeof AuthenticatedStudentHomeRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentRequestRoute: typeof AuthenticatedStudentRequestRoute
  AuthenticatedStudentSuggestLocationRoute: typeof AuthenticatedStudentSuggestLocationRoute
  AuthenticatedStudentRidesIdRoute: typeof AuthenticatedStudentRidesIdRoute
  AuthenticatedStudentRidesIndexRoute: typeof AuthenticatedStudentRidesIndexRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentActivityRoute: AuthenticatedStudentActivityRoute,
  AuthenticatedStudentHomeRoute: AuthenticatedStudentHomeRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedStudentRequestRoute: AuthenticatedStudentRequestRoute,
  AuthenticatedStudentSuggestLocationRoute:
    AuthenticatedStudentSuggestLocationRoute,
  AuthenticatedStudentRidesIdRoute: AuthenticatedStudentRidesIdRoute,
  AuthenticatedStudentRidesIndexRoute: AuthenticatedStudentRidesIndexRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountSetupRoute: typeof AuthenticatedAccountSetupRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedRiderRoute: typeof AuthenticatedRiderRouteWithChildren
  AuthenticatedRiderApplicationRoute: typeof AuthenticatedRiderApplicationRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountSetupRoute: AuthenticatedAccountSetupRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedRiderRoute: AuthenticatedRiderRouteWithChildren,
  AuthenticatedRiderApplicationRoute: AuthenticatedRiderApplicationRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountTypeRoute: AccountTypeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RiderSignupRoute: RiderSignupRoute,
  SignupRoute: SignupRoute,
  VerificationRoute: VerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
